export const brandsImg = [
	{
		alt: 'Gucci',
		src: '/assets/images/brands/gucci.svg',
	},
	{
		alt: 'Versace',
		src: '/assets/images/brands/versace.svg',
	},
	{
		alt: 'Calvin Klein',
		src: '/assets/images/brands/calvin-klein.svg',
	},
	{
		alt: 'Prada',
		src: '/assets/images/brands/prada.svg',
	},
	{
		alt: 'Zara',
		src: '/assets/images/brands/zara.svg',
	},
];

export const homepageSellingList = [
	{
		id: 1,
		title: 'Top Selling',
		data: [
			{
				id: 1,
				title: 'Gucci',
				image: '/assets/images/hero-1.svg',
				price: 52,
				rating: 4.5,
				brand: 'Gucci',
				description: '',
				category: '',
				numReviews: 0,
				countInStock: 0,
				isOutOfStock: false,
				isLimitedStock: false,
				path: '',
			},
			{
				id: 2,
				title: 'Versace',
				image: '/assets/images/hero-2.svg',
				price: 52,
				rating: 4.5,
				brand: 'Versace',
				description: '',
				category: '',
				numReviews: 0,
				countInStock: 0,
				isOutOfStock: false,
				isLimitedStock: false,
				path: '',
			},
			{
				id: 3,
				title: 'Calvin Klein',
				image: '/assets/images/hero-3.svg',
				price: 52,
				rating: 4.5,
				brand: '',
				description: '',
				category: '',
				numReviews: 0,
				countInStock: 0,
				isOutOfStock: false,
				isLimitedStock: false,
				path: '',
			},
			{
				id: 5,
				title: 'Zara',
				image: '/assets/images/hero-5.svg',
				price: 52,
				rating: 4.5,
				brand: '',
				description: '',
				category: '',
				numReviews: 0,
				countInStock: 0,
				isOutOfStock: false,
				isLimitedStock: false,
				path: '',
			},
		],
	},
	{
		id: 1,
		title: 'New arrivals',
		data: [
			{
				id: 1,
				title: 'Gucci',
				image: '/assets/Imgs/pants1.jpg',
				price: 52,
				rating: 4.5,
			},
			{
				id: 2,
				title: 'Versace',
				image: '/assets/Imgs/pants2.jpg',
				price: 52,
				rating: 4.5,
			},
			{
				id: 3,
				title: 'Calvin Klein',
				image: '/assets/Imgs/pants3.jpg',
				price: 52,
				rating: 4.5,
			},
			{
				id: 4,
				title: 'Prada',
				image: '/assets/Imgs/shirt1.jpg',
				price: 52,
				rating: 4.5,
			},
			{
				id: 5,
				title: 'Zara',
				image: '/assets/Imgs/shirt2.jpg',
				price: 52,
				rating: 4.5,
			},
		],
	},
];
