import '../globals.css';
import type { Metadata } from 'next';

import { ClerkProvider } from '@clerk/nextjs';

import { Tenor_Sans } from 'next/font/google';
import Navbar from '@/components/navigation/Navbar';
import HeaderBar from '@/components/navigation/HeaderBar';

const tenorSans = Tenor_Sans({
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Need.It',
	description: 'Generated by create next app',
};

export default function ShopLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang='fr'>
				<body className={`${tenorSans.className} max-w-10xl mx-auto`}>
					<HeaderBar />
					<main className='main-container'>{children}</main>
				</body>
			</html>
		</ClerkProvider>
	);
}
