import '../globals.css';
import type { Metadata } from 'next';

import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { frFR } from '@clerk/localizations'

import { Tenor_Sans } from 'next/font/google';
import Navbar from '@/components/navigation/Navbar';
import HeaderBar from '@/components/navigation/HeaderBar';

const tenorSans = Tenor_Sans({
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Need.It',
	description: 'Generated by create next app',
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider
			localization={frFR}
			appearance={{
				baseTheme: dark,
			}}>
			<html lang='fr'>
				<body className={`${tenorSans.className} bg-gray-950`}>
					<HeaderBar />
					<div className='w-full h-full flex justify-center items-center'>
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
