import '../globals.css';
import type { Metadata } from 'next';

import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

import { Tenor_Sans } from 'next/font/google';
import Navbar from '@/components/Navbar';

const tenorSans = Tenor_Sans({
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Need.It',
	description: 'Generated by create next app',
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider
			appearance={{
				baseTheme: dark,
			}}>
			<html lang='fr'>
				<body className={`${tenorSans.className} bg-gray-950`}>
					<header className='sticky top-0 w-full z-20 bg-gray-800 text-white px-6 py-3 drop-shadow-md'>
						<Navbar />
					</header>
					<div className='w-full h-full flex justify-center items-center'>
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
